import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  fr: {
    // Navbar
    home: 'Accueil', films: 'Films', cinemas: 'Cinémas', offers: 'Offres', about: 'À propos',
    aiPick: '✦ Choix IA', signIn: 'Se connecter', join: 'Rejoindre',
    profile: 'Profil', myBookings: 'Mes réservations', favourites: 'Favoris',
    signOut: 'Se déconnecter', search: 'Rechercher',
    searchPlaceholder: 'Rechercher films, genres, réalisateurs...',
    // Home
    nowShowing: 'À l\'affiche', comingSoon: 'Prochainement', allFilms: 'Tous les films',
    viewAll: 'Voir tout', bookTickets: 'Réserver', trailer: 'Bande-annonce',
    learnMore: 'En savoir plus', min: 'min',
    joinLoyalty: 'Rejoignez le programme de fidélité Al-Qumra',
    loyaltySub: 'Gagnez des points à chaque réservation. Débloquez les avantages Or & Platine, les sièges prioritaires et les séances exclusives.',
    joinFree: 'Rejoindre gratuitement',
    // Movies page
    nowShowingTab: 'À l\'affiche', comingSoonTab: 'Prochainement',
    searchTitleDirector: 'Rechercher titre ou réalisateur…',
    allGenres: 'Tous les genres', allTypes: 'Tous les types', allYears: 'Toutes les années',
    sortRating: 'Trier : Note', sortYear: 'Trier : Année',
    filmsFound: 'film(s) trouvé(s)', noFilmsMatch: 'Aucun film ne correspond.',
    clearFilters: 'Effacer les filtres', bookNow: 'Réserver',
    directedBy: 'Réalisé par', cast: 'Casting',
    watchTrailer: 'Voir la bande-annonce', closeTrailer: 'Fermer',
    bookSession: 'Réserver une séance', chooseSeats: 'Choisir les places',
    filmNotFound: 'Film introuvable.', backToCatalogue: 'Retour au catalogue',
    // Cinemas
    viewSessions: 'Voir les séances', sessions: 'Séances',
    noSessions: 'Aucune séance programmée.', cinemaNotFound: 'Cinéma introuvable.',
    // SeatMap
    nowShowingScreen: 'À L\'AFFICHE',
    available: 'Disponible', selected: 'Sélectionné', occupied: 'Occupé', vip: 'VIP',
    selectSeatHint: 'Cliquez sur un siège pour le sélectionner',
    proceedCheckout: 'Passer à la caisse',
    seat: 'siège', seats: 'sièges', sessionNotFound: 'Séance introuvable.',
    // Checkout
    checkout: 'Paiement', orderSummary: 'Récapitulatif', payment: 'Paiement',
    promoCode: 'Code promo (essayez QUMRA10)', apply: 'Appliquer',
    discountApplied: '10% de réduction appliquée !',
    subtotal: 'Sous-total', discount: 'Réduction (10%)', total: 'Total',
    cardNumber: 'Numéro de carte', expiry: 'Expiration', cvc: 'CVC',
    demoMode: '🔒 Mode démo — aucun paiement réel',
    pay: 'Payer', processing: 'Traitement...', paymentConfirmed: '✓ Paiement confirmé !',
    noBooking: 'Aucune réservation en cours.',
    // Booking confirm
    bookingConfirmed: 'Réservation confirmée !',
    showAtEntrance: 'Présentez ceci à l\'entrée',
    totalPaid: 'Total payé', status: 'Statut', confirmed: 'Confirmé',
    // Booking history
    myBookingsTitle: 'Mes réservations', noBookingsYet: 'Aucune réservation.',
    browseFilms: 'Parcourir les films', resell: 'Revendre',
    // Profile
    memberSince: 'Membre depuis', filmsWatched: 'Films vus',
    loyaltyPoints: 'Points fidélité', tier: 'Niveau',
    resellTicket: 'Revendre un ticket',
    // Login
    welcomeBack: 'Bon retour', signInAccount: 'Connectez-vous à votre compte',
    forgotPassword: 'Mot de passe oublié ?', signingIn: 'Connexion...', signInBtn: 'Se connecter',
    noAccount: 'Pas de compte ?', joinAlQumra: 'Rejoindre Al-Qumra',
    continueGoogle: 'Continuer avec Google', orDivider: 'ou',
    // Register
    joinTitle: 'Rejoindre Al-Qumra', createAccount: 'Créer votre compte',
    fullName: 'Nom complet', password: 'Mot de passe', confirm: 'Confirmer',
    creatingAccount: 'Création du compte...', createAccountBtn: 'Créer un compte',
    alreadyMember: 'Déjà membre ?',
    // Reset password
    resetPassword: 'Réinitialiser le mot de passe',
    resetSub: 'Entrez votre email et nous vous enverrons les instructions',
    sendResetLink: 'Envoyer le lien', checkEmail: 'Vérifiez votre email',
    resetSent: 'Nous avons envoyé les instructions à',
    backToSignIn: 'Retour à la connexion',
    // AI Recommend
    aiFilmPicker: 'Sélecteur de films IA',
    aiSub: 'Dites-nous votre humeur et nous choisirons le film parfait pour ce soir.',
    genrePreference: 'Genre préféré', filmType: 'Type de film', tonightsMood: 'Humeur du soir',
    moods: ['Excitant', 'Réfléchi', 'Fun & Léger', 'Émouvant', 'Effrayant'],
    analysing: 'Analyse...', generatePicks: 'Générer des suggestions',
    aiCurating: 'Notre IA sélectionne des films pour vous…',
    yourPicksTonight: 'Vos sélections ce soir', pick: 'Sélection',
    clearPicks: 'Effacer',
    // Offers
    expiresIn: 'Expire dans', claimOffer: 'Obtenir l\'offre', claimed: '✓ Obtenu',
    earnMore: 'Gagnez plus avec Al-Qumra Loyalty',
    earnMoreSub: 'Notre façon de vous remercier, à chaque fois.',
    // Resell
    resellTitle: 'Revendre un ticket',
    resellNote: 'Revendre un ticket annulera votre réservation. Vous recevrez un remboursement de 50% du prix.',
    selectBooking: 'Sélectionner la réservation à revendre',
    chooseBooking: '-- Choisir une réservation --',
    estimatedRefund: 'Remboursement estimé :',
    confirmResell: 'Confirmer la revente',
    ticketListed: 'Ticket mis en vente !',
    ticketListedSub: 'Votre ticket a été soumis. Vous recevrez 50% du prix original une fois revendu.',
    // Feedback
    submitFeedback: 'Soumettre un avis',
    yourRating: 'Votre note', filmSession: 'Film / Séance',
    yourComment: 'Votre commentaire', shareExperience: 'Partagez votre expérience…',
    submitFeedbackBtn: 'Soumettre', thankYou: 'Merci !',
    feedbackHelps: 'Votre avis nous aide à améliorer Al-Qumra.',
    // Favorites
    myFavourites: 'Mes favoris',
    // Staff
    todaysSessions: 'Séances du jour', qrScanner: 'Scanner QR',
    walkInBooking: 'Réservation sur place', staffPortal: 'PORTAIL STAFF',
    exitToSite: 'Retour au site', film: 'Film', cinema: 'Cinéma',
    hall: 'Salle', time: 'Heure', format: 'Format', price: 'Prix',
    pointCamera: 'Pointez la caméra sur le QR du ticket',
    qrNote: 'En production, cela activerait votre caméra pour la validation en temps réel.',
    typeBookingId: 'Ou tapez l\'ID de réservation manuellement…',
    validate: 'Valider', session: 'Séance', customerName: 'Nom du client',
    seatLabel: 'Siège', paymentMethod: 'Mode de paiement',
    cash: 'Espèces', card: 'Carte (TPE)',
    confirmWalkIn: 'Confirmer la réservation',
    // Footer
    explore: 'Explorer', account: 'Compte', contact: 'Contact',
    nowShowingFooter: 'À l\'affiche', comingSoonFooter: 'Prochainement',
    ourCinemas: 'Nos cinémas', aiPicks: 'Choix IA',
    loyaltyCard: 'Carte fidélité',
  },

  en: {
    home: 'Home', films: 'Films', cinemas: 'Cinemas', offers: 'Offers', about: 'About',
    aiPick: '✦ AI Pick', signIn: 'Sign In', join: 'Join',
    profile: 'Profile', myBookings: 'My Bookings', favourites: 'Favourites',
    signOut: 'Sign Out', search: 'Search',
    searchPlaceholder: 'Search films, genres, directors...',
    nowShowing: 'Now Showing', comingSoon: 'Coming Soon', allFilms: 'All Films',
    viewAll: 'View All', bookTickets: 'Book Tickets', trailer: 'Trailer',
    learnMore: 'Learn More', min: 'min',
    joinLoyalty: 'Join the Al-Qumra Loyalty Programme',
    loyaltySub: 'Earn points on every booking. Unlock Gold & Platinum perks, priority seating, and exclusive screenings.',
    joinFree: 'Join Free',
    nowShowingTab: 'Now Showing', comingSoonTab: 'Coming Soon',
    searchTitleDirector: 'Search title or director…',
    allGenres: 'All Genres', allTypes: 'All Types', allYears: 'All Years',
    sortRating: 'Sort: Rating', sortYear: 'Sort: Year',
    filmsFound: 'film(s) found', noFilmsMatch: 'No films match your criteria.',
    clearFilters: 'Clear Filters', bookNow: 'Book Now',
    directedBy: 'Directed by', cast: 'Cast',
    watchTrailer: 'Watch Trailer', closeTrailer: 'Close Trailer',
    bookSession: 'Book a Session', chooseSeats: 'Choose Seats',
    filmNotFound: 'Film not found.', backToCatalogue: 'Back to Catalogue',
    viewSessions: 'View Sessions', sessions: 'Sessions',
    noSessions: 'No sessions scheduled.', cinemaNotFound: 'Cinema not found.',
    nowShowingScreen: 'NOW SHOWING',
    available: 'Available', selected: 'Selected', occupied: 'Occupied', vip: 'VIP',
    selectSeatHint: 'Click a seat to select it',
    proceedCheckout: 'Proceed to Checkout',
    seat: 'seat', seats: 'seats', sessionNotFound: 'Session not found.',
    checkout: 'Checkout', orderSummary: 'Order Summary', payment: 'Payment',
    promoCode: 'Promo code (try QUMRA10)', apply: 'Apply',
    discountApplied: '10% discount applied!',
    subtotal: 'Subtotal', discount: 'Discount (10%)', total: 'Total',
    cardNumber: 'Card Number', expiry: 'Expiry', cvc: 'CVC',
    demoMode: '🔒 Demo mode — no real payment processed',
    pay: 'Pay', processing: 'Processing…', paymentConfirmed: '✓ Payment Confirmed!',
    noBooking: 'No booking in progress.',
    bookingConfirmed: 'Booking Confirmed!',
    showAtEntrance: 'Show this at the entrance',
    totalPaid: 'Total Paid', status: 'Status', confirmed: 'Confirmed',
    myBookingsTitle: 'My Bookings', noBookingsYet: 'No bookings yet.',
    browseFilms: 'Browse Films', resell: 'Resell',
    memberSince: 'Member since', filmsWatched: 'Films Watched',
    loyaltyPoints: 'Loyalty Points', tier: 'Tier', resellTicket: 'Resell Ticket',
    welcomeBack: 'Welcome Back', signInAccount: 'Sign in to your account',
    forgotPassword: 'Forgot password?', signingIn: 'Signing in…', signInBtn: 'Sign In',
    noAccount: 'Don\'t have an account?', joinAlQumra: 'Join Al-Qumra',
    continueGoogle: 'Continue with Google', orDivider: 'or',
    joinTitle: 'Join Al-Qumra', createAccount: 'Create your account',
    fullName: 'Full Name', password: 'Password', confirm: 'Confirm',
    creatingAccount: 'Creating account…', createAccountBtn: 'Create Account',
    alreadyMember: 'Already a member?',
    resetPassword: 'Reset Password',
    resetSub: 'Enter your email and we\'ll send instructions',
    sendResetLink: 'Send Reset Link', checkEmail: 'Check your email',
    resetSent: 'We\'ve sent reset instructions to',
    backToSignIn: 'Back to Sign In',
    aiFilmPicker: 'AI Film Picker',
    aiSub: 'Tell us how you feel and we\'ll pick the perfect film for tonight.',
    genrePreference: 'Genre preference', filmType: 'Film type', tonightsMood: 'Tonight\'s mood',
    moods: ['Exciting', 'Thoughtful', 'Fun & Light', 'Emotional', 'Scary'],
    analysing: 'Analysing…', generatePicks: 'Generate Picks',
    aiCurating: 'Our AI is curating films for you…',
    yourPicksTonight: 'Your Picks Tonight', pick: 'Pick', clearPicks: 'Clear Picks',
    expiresIn: 'Expires in', claimOffer: 'Claim Offer', claimed: '✓ Claimed',
    earnMore: 'Earn More with Al-Qumra Loyalty',
    earnMoreSub: 'Our way of saying thank you, every time.',
    resellTitle: 'Resell a Ticket',
    resellNote: 'Reselling a ticket will cancel your booking. You will receive a 50% refund.',
    selectBooking: 'Select Booking to Resell',
    chooseBooking: '-- Choose a booking --',
    estimatedRefund: 'Estimated refund:',
    confirmResell: 'Confirm Resell',
    ticketListed: 'Ticket Listed!',
    ticketListedSub: 'Your ticket has been submitted. You will receive 50% once resold.',
    submitFeedback: 'Submit Feedback',
    yourRating: 'Your Rating', filmSession: 'Film / Session',
    yourComment: 'Your Comment', shareExperience: 'Share your experience…',
    submitFeedbackBtn: 'Submit', thankYou: 'Thank you!',
    feedbackHelps: 'Your feedback helps us improve Al-Qumra Cinema.',
    myFavourites: 'My Favourites',
    todaysSessions: 'Today\'s Sessions', qrScanner: 'QR Scanner',
    walkInBooking: 'Walk-in Booking', staffPortal: 'STAFF PORTAL',
    exitToSite: 'Exit to Site', film: 'Film', cinema: 'Cinema',
    hall: 'Hall', time: 'Time', format: 'Format', price: 'Price',
    pointCamera: 'Point camera at ticket QR code',
    qrNote: 'In production, this would activate your device camera for real-time ticket validation.',
    typeBookingId: 'Or type booking ID manually…',
    validate: 'Validate', session: 'Session', customerName: 'Customer Name',
    seatLabel: 'Seat', paymentMethod: 'Payment Method',
    cash: 'Cash', card: 'Card (TPE)',
    confirmWalkIn: 'Confirm Walk-in Booking',
    explore: 'Explore', account: 'Account', contact: 'Contact',
    nowShowingFooter: 'Now Showing', comingSoonFooter: 'Coming Soon',
    ourCinemas: 'Our Cinemas', aiPicks: 'AI Picks',
    loyaltyCard: 'Loyalty Card',
  },

  ar: {
    home: 'الرئيسية', films: 'الأفلام', cinemas: 'دور السينما', offers: 'العروض', about: 'عن القُمرة',
    aiPick: '✦ اختيار الذكاء', signIn: 'تسجيل الدخول', join: 'انضم',
    profile: 'الملف الشخصي', myBookings: 'حجوزاتي', favourites: 'المفضلة',
    signOut: 'تسجيل الخروج', search: 'بحث',
    searchPlaceholder: 'ابحث عن أفلام، أنواع، مخرجين...',
    nowShowing: 'يُعرض الآن', comingSoon: 'قريباً', allFilms: 'كل الأفلام',
    viewAll: 'عرض الكل', bookTickets: 'احجز تذاكر', trailer: 'إعلان',
    learnMore: 'اكتشف المزيد', min: 'د',
    joinLoyalty: 'انضم إلى برنامج ولاء القُمرة',
    loyaltySub: 'اكسب نقاطاً في كل حجز. احصل على مزايا الذهب والبلاتين ومقاعد ذات أولوية وعروض حصرية.',
    joinFree: 'انضم مجاناً',
    nowShowingTab: 'يُعرض الآن', comingSoonTab: 'قريباً',
    searchTitleDirector: 'ابحث بالعنوان أو المخرج…',
    allGenres: 'كل الأنواع', allTypes: 'كل الأنواع', allYears: 'كل السنوات',
    sortRating: 'ترتيب: التقييم', sortYear: 'ترتيب: السنة',
    filmsFound: 'فيلم موجود', noFilmsMatch: 'لا توجد أفلام تطابق معاييرك.',
    clearFilters: 'مسح الفلاتر', bookNow: 'احجز الآن',
    directedBy: 'إخراج', cast: 'طاقم التمثيل',
    watchTrailer: 'مشاهدة الإعلان', closeTrailer: 'إغلاق',
    bookSession: 'احجز عرضاً', chooseSeats: 'اختر المقاعد',
    filmNotFound: 'الفيلم غير موجود.', backToCatalogue: 'العودة للكتالوج',
    viewSessions: 'عرض الجلسات', sessions: 'الجلسات',
    noSessions: 'لا توجد جلسات مجدولة.', cinemaNotFound: 'السينما غير موجودة.',
    nowShowingScreen: 'يُعرض الآن',
    available: 'متاح', selected: 'محدد', occupied: 'محجوز', vip: 'VIP',
    selectSeatHint: 'انقر على مقعد لتحديده',
    proceedCheckout: 'المتابعة للدفع',
    seat: 'مقعد', seats: 'مقاعد', sessionNotFound: 'الجلسة غير موجودة.',
    checkout: 'الدفع', orderSummary: 'ملخص الطلب', payment: 'الدفع',
    promoCode: 'كود الخصم (جرب QUMRA10)', apply: 'تطبيق',
    discountApplied: 'تم تطبيق خصم 10%!',
    subtotal: 'المجموع الجزئي', discount: 'الخصم (10%)', total: 'الإجمالي',
    cardNumber: 'رقم البطاقة', expiry: 'تاريخ الانتهاء', cvc: 'CVC',
    demoMode: '🔒 وضع تجريبي — لا يتم معالجة أي دفع حقيقي',
    pay: 'ادفع', processing: 'جارٍ المعالجة…', paymentConfirmed: '✓ تم تأكيد الدفع!',
    noBooking: 'لا يوجد حجز جارٍ.',
    bookingConfirmed: 'تم تأكيد الحجز!',
    showAtEntrance: 'أظهر هذا عند المدخل',
    totalPaid: 'المبلغ المدفوع', status: 'الحالة', confirmed: 'مؤكد',
    myBookingsTitle: 'حجوزاتي', noBookingsYet: 'لا توجد حجوزات بعد.',
    browseFilms: 'تصفح الأفلام', resell: 'إعادة البيع',
    memberSince: 'عضو منذ', filmsWatched: 'أفلام مشاهدة',
    loyaltyPoints: 'نقاط الولاء', tier: 'المستوى', resellTicket: 'إعادة بيع تذكرة',
    welcomeBack: 'مرحباً بعودتك', signInAccount: 'سجّل دخولك',
    forgotPassword: 'نسيت كلمة المرور؟', signingIn: 'جارٍ الدخول…', signInBtn: 'تسجيل الدخول',
    noAccount: 'ليس لديك حساب؟', joinAlQumra: 'انضم إلى القُمرة',
    continueGoogle: 'المتابعة مع Google', orDivider: 'أو',
    joinTitle: 'انضم إلى القُمرة', createAccount: 'أنشئ حسابك',
    fullName: 'الاسم الكامل', password: 'كلمة المرور', confirm: 'تأكيد',
    creatingAccount: 'جارٍ إنشاء الحساب…', createAccountBtn: 'إنشاء حساب',
    alreadyMember: 'عضو بالفعل؟',
    resetPassword: 'إعادة تعيين كلمة المرور',
    resetSub: 'أدخل بريدك وسنرسل لك التعليمات',
    sendResetLink: 'إرسال رابط الإعادة', checkEmail: 'تحقق من بريدك',
    resetSent: 'أرسلنا تعليمات الإعادة إلى',
    backToSignIn: 'العودة لتسجيل الدخول',
    aiFilmPicker: 'مختار الأفلام الذكي',
    aiSub: 'أخبرنا بمزاجك وسنختار لك الفيلم المثالي الليلة.',
    genrePreference: 'النوع المفضل', filmType: 'نوع الفيلم', tonightsMood: 'مزاج الليلة',
    moods: ['مثير', 'مدروس', 'مرح وخفيف', 'عاطفي', 'مرعب'],
    analysing: 'جارٍ التحليل…', generatePicks: 'توليد الاقتراحات',
    aiCurating: 'ذكاؤنا الاصطناعي يختار الأفلام لك…',
    yourPicksTonight: 'اختياراتك الليلة', pick: 'اختيار', clearPicks: 'مسح',
    expiresIn: 'تنتهي في', claimOffer: 'احصل على العرض', claimed: '✓ تم الحصول',
    earnMore: 'اكسب أكثر مع ولاء القُمرة',
    earnMoreSub: 'طريقتنا في شكرك، في كل مرة.',
    resellTitle: 'إعادة بيع تذكرة',
    resellNote: 'إعادة البيع ستلغي حجزك. ستحصل على استرداد 50% من السعر.',
    selectBooking: 'اختر الحجز لإعادة البيع',
    chooseBooking: '-- اختر حجزاً --',
    estimatedRefund: 'الاسترداد المتوقع:',
    confirmResell: 'تأكيد إعادة البيع',
    ticketListed: 'تم عرض التذكرة!',
    ticketListedSub: 'تم تقديم تذكرتك. ستحصل على 50% بعد البيع.',
    submitFeedback: 'إرسال تقييم',
    yourRating: 'تقييمك', filmSession: 'الفيلم / الجلسة',
    yourComment: 'تعليقك', shareExperience: 'شارك تجربتك…',
    submitFeedbackBtn: 'إرسال', thankYou: 'شكراً!',
    feedbackHelps: 'تقييمك يساعدنا على تحسين القُمرة.',
    myFavourites: 'مفضلتي',
    todaysSessions: 'جلسات اليوم', qrScanner: 'ماسح QR',
    walkInBooking: 'حجز مباشر', staffPortal: 'بوابة الموظفين',
    exitToSite: 'الخروج للموقع', film: 'الفيلم', cinema: 'السينما',
    hall: 'القاعة', time: 'الوقت', format: 'الصيغة', price: 'السعر',
    pointCamera: 'وجّه الكاميرا نحو QR التذكرة',
    qrNote: 'في الإنتاج، سيُفعّل كاميرا جهازك للتحقق الفوري.',
    typeBookingId: 'أو اكتب رقم الحجز يدوياً…',
    validate: 'تحقق', session: 'الجلسة', customerName: 'اسم العميل',
    seatLabel: 'المقعد', paymentMethod: 'طريقة الدفع',
    cash: 'نقداً', card: 'بطاقة (TPE)',
    confirmWalkIn: 'تأكيد الحجز المباشر',
    explore: 'استكشف', account: 'الحساب', contact: 'التواصل',
    nowShowingFooter: 'يُعرض الآن', comingSoonFooter: 'قريباً',
    ourCinemas: 'دور السينما', aiPicks: 'اختيارات الذكاء',
    loyaltyCard: 'بطاقة الولاء',
  },
};

const LANGS = ['fr', 'en', 'ar'];
const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('alqumra-lang') || 'fr');

  useEffect(() => {
    document.documentElement.setAttribute('lang', lang);
    document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    localStorage.setItem('alqumra-lang', lang);
  }, [lang]);

  const t = (key) => translations[lang]?.[key] ?? translations['fr']?.[key] ?? key;
  const toggleLang = () => setLang(l => LANGS[(LANGS.indexOf(l) + 1) % LANGS.length]);
  const setLangDirect = (l) => setLang(l);

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang, setLangDirect, LANGS }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);

export function useMovieField() {
  const { lang } = useLang();
  return (movie, field) => {
    if (lang === 'fr' && movie[`${field}_fr`]) return movie[`${field}_fr`];
    if (lang === 'ar' && movie[`${field}_ar`]) return movie[`${field}_ar`];
    return movie[field];
  };
}